[package]
name = "myapp"
version = "1.0.0"
authors = ["Lena Schimmel <mail@lenaschimmel.de>", "Kirstin Rohwer <mail@metakiki.net>"]
edition = "2018"

[dependencies]
gtfs-rt = "0.1.0"
prost = "0.4"
bytes = "0.5.4"
csv = "1.1.3"
serde = { version = "1", features = ["derive"] }